# Generated by Django 4.2.29 on 2026-03-19 22:08

import apps.guardados.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('juegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('JAP', 'Japón'), ('USA', 'USA'), ('EUR', 'Europa')], max_length=3, verbose_name='Región')),
                ('archivo', models.FileField(upload_to=apps.guardados.models.ruta_guardado, validators=[apps.guardados.models._validar_ext_basica], verbose_name='Archivo')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('num_descargas', models.PositiveIntegerField(default=0, verbose_name='Descargas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados', to='juegos.juego', verbose_name='Juego')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'ordering': ['-subido_en'],
                'verbose_name': 'Archivo de guardado',
                'verbose_name_plural': 'Archivos de guardado',
            },
        ),
    ]
