# Generated by Django 4.2.29 on 2026-03-19 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('slug', models.CharField(choices=[('NES', 'NES'), ('MASTER_SYSTEM', 'Master System'), ('GB', 'Game Boy'), ('GAME_GEAR', 'Game Gear'), ('SNES', 'SNES'), ('MEGADRIVE', 'Megadrive'), ('PS1', 'PlayStation 1'), ('SEGA_SATURN', 'Sega Saturn'), ('N64', 'Nintendo 64'), ('GBC', 'Game Boy Color'), ('GBA', 'Game Boy Advance'), ('GAME_CUBE', 'GameCube'), ('PS2', 'PlayStation 2'), ('XBOX', 'Xbox'), ('XBOX_360', 'Xbox 360'), ('PSP', 'PSP'), ('PS3', 'PlayStation 3'), ('NDS', 'Nintendo DS'), ('WII', 'Wii'), ('WIIU', 'Wii U'), ('NINTENDO_3DS', 'Nintendo 3DS'), ('PS4', 'PlayStation 4'), ('XBOX_ONE', 'Xbox One')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(editable=False, max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('desarrollador', models.CharField(blank=True, max_length=100, verbose_name='Desarrollador')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Publicador')),
                ('num_jugadores', models.PositiveSmallIntegerField(default=1, verbose_name='Jugadores')),
                ('visitas', models.PositiveIntegerField(default=0, verbose_name='Visitas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('portada_url', models.URLField(blank=True, max_length=500, verbose_name='URL de portada (IGDB)')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos', to='juegos.genero', verbose_name='Género')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='juegos.plataforma', verbose_name='Plataforma')),
            ],
            options={
                'ordering': ['titulo'],
                'unique_together': {('titulo', 'plataforma')},
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='CapturaPantalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('añadido', models.DateTimeField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='juegos.juego')),
            ],
            options={
                'ordering': ['orden', 'añadido'],
                'verbose_name': 'Captura de pantalla',
                'verbose_name_plural': 'Capturas de pantalla',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000, verbose_name='Comentario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('editado_en', models.DateTimeField(auto_now=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='juegos.juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
