# Generated by Django 4.2.29 on 2026-04-02 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
        ('guardados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En revisión'), ('resolved', 'Resuelto'), ('dismissed', 'Descartado')], default='pending', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('resuelto_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('motivo', models.CharField(choices=[('spam', 'Spam o autopromoción'), ('abuso', 'Abuso, insultos o lenguaje inapropiado'), ('irrelevante', 'Irrelevante para el juego'), ('informacion_falsa', 'Información falsa o engañosa'), ('otro', 'Otro')], max_length=20, verbose_name='Motivo')),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_comentario', to='juegos.comentario', verbose_name='Comentario')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_hechos', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Reporte de comentario',
                'verbose_name_plural': 'Reportes de comentarios',
                'unique_together': {('comentario', 'reportado_por')},
            },
        ),
        migrations.CreateModel(
            name='ReporteGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, max_length=500, verbose_name='Detalle')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En revisión'), ('resolved', 'Resuelto'), ('dismissed', 'Descartado')], default='pending', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('resuelto_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('motivo', models.CharField(choices=[('broken', 'Archivo roto/corrupto'), ('wrong_game', 'Juego incorrecto'), ('malware', 'Sospechoso/Malware'), ('wrong_region', 'Región incorrecta'), ('other', 'Otro')], max_length=20, verbose_name='Motivo')),
                ('archivo_guardado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_guardado', to='guardados.archivoguardado', verbose_name='Archivo de guardado')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_hechos', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resueltos', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
            ],
            options={
                'verbose_name': 'Reporte de guardado',
                'verbose_name_plural': 'Reportes de guardados',
                'unique_together': {('archivo_guardado', 'reportado_por')},
            },
        ),
    ]
